#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# presume schemas is a sibling of this codebase
# make use of the extra "proto" directory that CH has put in there
DEST=$DIR/..
SRC=$DIR/../../schemas/src/main/resources

if [ ! -d $DEST/proto ] ; then
    echo "Can't find destination python directory $DEST/proto"
    exit 1
fi

if [ ! -d $SRC ] ; then
    echo "Can't find source proto directory $SRC"
    exit 2
fi


cd $SRC

protoc -I . --python_out=$DEST proto/{,*/}*/*.proto

cd $DEST/proto
for d in `find . -type d` ; do
    touch $d/__init__.py
done